name: Job Bot

on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: pip install -r requirements.txt

      - name: Load previous jobs
        uses: actions/cache@v4
        with:
          path: sent_jobs.json
          key: jobs-cache

      - run: python CatalinaJob.py   # <-- make sure this matches your file

      - name: Save jobs
        uses: actions/cache@v4
        with:
          path: sent_jobs.json
          key: jobs-cache
